/*
-- Query: SELECT * FROM recipedb.recipes
LIMIT 0, 1000

-- Date: 2023-10-23 21:58
*/
USE recipedb;
INSERT INTO `recipes` (`recipe_id`,`name`,`instructions`,`image_url`) VALUES (1,'Dooky Chase-Style Fried Chicken','ahahaghahahahahahahahahhhhhhhhhhhhhhhhhhaaaaaaaaaaaaaaaaaa\r\n\r\nahahaghahahahahahahahahhhhhhhhhhhhhhhhhhaaaaaaaaaaaaaaaaaa\r\n\r\nahahaghahahahahahahahahhhhhhhhhhhhhhhhhhaaaaaaaaaaaaaaaaaa\r\n\r\nahahaghahahahahahahahahhhhhhhhhhhhhhhhhhaaaaaaaaaaaaaaaaaa\r\nahahaghahahahahahahahahhhhhhhhhhhhhhhhhhaaaaaaaaaaaaaaaaaa\r\nahahaghahahahahahahahahhhhhhhhhhhhhhhhhhaaaaaaaaaaaaaaaaaa\r\nahahaghahahahahahahahahhhhhhhhhhhhhhhhhhaaaaaaaaaaaaaaaaaa\r\nahahaghahahahahahahahahhhhhhhhhhhhhhhhhhaaaaaaaaaaaaaaaaaaahahaghahahahahahahahahhhhhhhhhhhhhhhhhhaaaaaaaaaaaaaaaaaaahahaghahahahahahahahahhhhhhhhhhhhhhhhhhaaaaaaaaaaaaaaaaaaahahaghahahahahahahahahhhhhhhhhhhhhhhhhhaaaaaaaaaaaaaaaaaaahahaghahahahahahahahahhhhhhhhhhhhhhhhhhaaaaaaaaaaaaaaaaaaahahaghahahahahahahahahhhhhhhhhhhhhhhhhhaaaaaaaaaaaaaaaaaaahahaghahahahahahahahahhhhhhhhhhhhhhhhhhaaaaaaaaaaaaaaaaaaahahaghahahahahahahahahhhhhhhhhhhhhhhhhhaaaaaaaaaaaaaaaaaaahahaghahahahahahahahahhhhhhhhhhhhhhhhhhaaaaaaaaaaaaaaaaaaahahaghahahahahahahahahhhhhhhhhhhhhhhhhhaaaaaaaaaaaaaaaaaaahahaghahahahahahahahahhhhhhhhhhhhhhhhhhaaaaaaaaaaaaaaaaaaahahaghahahahahahahahahhhhhhhhhhhhhhhhhhaaaaaaaaaaaaaaaaaa','static/img-db/Dooky_Chase-Style_Fried_Chicken.jpg');
INSERT INTO `recipes` (`recipe_id`,`name`,`instructions`,`image_url`) VALUES (2,'Biko','Step 1:\r\n\r\nSoak rice overnight in the water.\r\n\r\nStep 2:\r\n\r\nPreheat oven to 350 degrees F (175 degrees C). Grease a 9x13 inch baking pan.\r\n\r\nStep 3:\r\n\r\nCook the soaked rice over medium heat in a saucepan with the soaking water, 1/2 can of coconut milk, and white sugar, stirring constantly, until tender and thickened, about 20 minutes. Pour into the prepared baking pan.\r\n\r\nStep 4:\r\n\r\nStir together the brown sugar, remaining 1/2 can of coconut milk, and coconut preserves in a small saucepan, and bring to a boil. Pour the mixture carefully over the rice.\r\n\r\nStep 5:\r\n\r\nBake in the preheated oven until the topping thickens, about 25 minutes. Cool completely; cut into squares to serve.\r\n\r\n','static/img-db/biko.jpg');
INSERT INTO `recipes` (`recipe_id`,`name`,`instructions`,`image_url`) VALUES (3,'Leche Flan','fasdfas','static/img-db/leche-flan.jpg');
INSERT INTO `recipes` (`recipe_id`,`name`,`instructions`,`image_url`) VALUES (4,'Rice Cake','fasdfas','static/img-db/rice-cakes.png');
INSERT INTO `recipes` (`recipe_id`,`name`,`instructions`,`image_url`) VALUES (5,'Balot','agfadsfasfasdfas','static/img-db/balot.jpg');
INSERT INTO `recipes` (`recipe_id`,`name`,`instructions`,`image_url`) VALUES (6,'Adobo','Step 1:\r\n\r\nHeat vegetable oil in a large skillet over medium-high heat. Cook chicken pieces until golden brown, 2 to 3 minutes per side. Transfer chicken to a plate and set aside.\r\n\r\nStep 2:\r\n\r\nAdd onion and garlic to the skillet; cook until softened and brown, about 6 minutes.\r\n\r\nstep 3:\r\n\r\nPour in soy sauce and vinegar and season with garlic powder, black pepper, and bay leaf.\r\n\r\nStep 4:\r\n\r\nReturn chicken to pan, increase heat to high, and bring to a boil. Reduce heat to medium-low, cover, and simmer until chicken is tender and cooked through, 35 to 40 minutes.\r\n\r\n\r\n\r\n','static/img-db/adobo.jpg');
INSERT INTO `recipes` (`recipe_id`,`name`,`instructions`,`image_url`) VALUES (13,'Lechon ','fasdfas','static/img-db/lechon.jpg');
INSERT INTO `recipes` (`recipe_id`,`name`,`instructions`,`image_url`) VALUES (14,'Pasta Fazool (Pasta e Fagioli)','asfdas','static/img-db/Pasta_Fazool_Pasta_e_Fagioli.png');
INSERT INTO `recipes` (`recipe_id`,`name`,`instructions`,`image_url`) VALUES (15,'Toron','asfdasd','static/img-db/toron.jpg');
INSERT INTO `recipes` (`recipe_id`,`name`,`instructions`,`image_url`) VALUES (16,'carrot na luto','fasdfas','static/img-db/carrot.jpg');